name: Build

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build
        id: build
        run: |
          bash ./scripts/check.sh
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ success() || failure() }}
        with:
          files: |
            library/lorcana-data/build/test-results/**/*.xml
